name: Update Oh My Zsh Aliases

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-aliases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Latest Aliases File
        run: curl -sSL "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/aliases/aliases.plugin.zsh" -o aliases.plugin.zsh

      - name: Check for Changes
        run: |
          git add aliases.plugin.zsh
          if git diff --cached --quiet; then
            echo "No changes detected. Exiting..."
            exit 0
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update aliases.plugin.zsh ($(date))"
          git push
